### ISSUE TITLE
CREATE and DOES> not available?

### ISSUE THREAD

**Issue by olleharstedt** [linkedin/forthic#10]
Just checking if this functionality was implemented in this dialect of Forth or not. :) If not, any plans to do it?

**Comment by rjose** [comment]
Hi, @olleharstedt. I designed Forthic so it acts as essentially a command dispatch language where words are executed as encountered, so it doesn't have words that do any lookahead. The only exception is when words are defined, though technically one could view something like `: NEW-WORD` as a particular kind of "literal" that starts a definition.

One benefit of this is that words in Forthic can be viewed as morphisms in Category Theory. Once you take this perspective, you can apply concepts from Category Theory to writing Forthic code, something I've called "Categorical Coding".

**Comment by olleharstedt** [comment]
Yea, in forth `:` can be written by Forth itself, I think. But I get that other limitations apply when making your own dialect for other purposes than Chuck imagined.

**Comment by rjose** [comment]
My original attempt at building Forthic was to build it to follow Forth _exactly_. But Forth isn't great at string handling, and a lot of what I do uses strings. So my second attempt was to add support for what I needed but in as minimalistic way as possible. But that led to code that was very unforgiving.

My current approach is to accept that Forthic will always have a host language like Python or Javascript and in having that, Forthic can focus entirely on being the application language. That split has allowed me to shunt "low level" code to the host language and keep Forthic at a "high level". It's surprising how much can be done at the high level. Plus, that leads right into Category Theory.
