### ISSUE TITLE
Add PHP backend

### ISSUE THREAD

**Issue by olleharstedt** [linkedin/forthic#11]
A bit interested how this could be done.

**Comment by rjose** [comment]
Hmmm...I'm not sure. I've never really used PHP before. If we were to follow the same pattern as Python/React, we'd need to build a Forthic interpreter using the PHP primitives and then use that interpreter to dynamically call PHP functions. I assume PHP is powerful enough to do this?

**Comment by olleharstedt** [comment]
Perhaps! My current approach to merging PHP and Forth is to use gforth to spit out PHP source code, like a metalanguage. Then I do have access to all the ins and outs of a full-fledged Forth system.

**Comment by rjose** [comment]
Good luck! If I find myself doing any PHP work, I'll circle back here :-)
